# Generated by Django 5.2.7 on 2025-10-23 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengumpulanTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_jawaban', models.FileField(blank=True, null=True, upload_to='tugas_siswa/')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_kumpul', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Menunggu Penilaian', max_length=20)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tugas')),
            ],
        ),
    ]
