# Generated by Django 5.2.7 on 2025-10-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruprofile',
            name='mapel',
            field=models.ManyToManyField(blank=True, related_name='pengajar_mapel', to='learning.mapel'),
        ),
        migrations.AlterField(
            model_name='guruprofile',
            name='kelas',
            field=models.ManyToManyField(blank=True, related_name='guru_kelas', to='learning.kelas'),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapel_diajarkan', to='learning.guruprofile'),
        ),
    ]
