# Generated by Django 5.2.7 on 2025-10-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_pengumpulantugas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bab',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='mapel/'),
        ),
    ]
