# Generated by Django 5.2.7 on 2025-10-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_guruprofile_mapel_alter_guruprofile_kelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengumpulantugas',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='pengumpulantugas',
            name='file_jawaban',
        ),
        migrations.RemoveField(
            model_name='pengumpulantugas',
            name='status',
        ),
        migrations.AddField(
            model_name='pengumpulantugas',
            name='file',
            field=models.FileField(default=1, upload_to='tugas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengumpulantugas',
            name='nilai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='tugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan', to='learning.tugas'),
        ),
    ]
