# Generated by Django 5.2.7 on 2025-10-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_pengumpulantugas_catatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='bab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='learning.bab'),
        ),
    ]
