# Generated by Django 5.2.7 on 2025-10-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_bab_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bab',
            name='gambar',
        ),
        migrations.AddField(
            model_name='mapel',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='mapel/'),
        ),
    ]
