# Generated by Django 5.2.7 on 2025-10-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_bab_gambar_mapel_deskripsi_mapel_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugas',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='tugas',
            name='bab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.bab'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='judul',
            field=models.CharField(max_length=100),
        ),
    ]
