# Generated by Django 5.2.7 on 2025-10-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_tugas_bab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='tugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan_tugas', to='learning.tugas'),
        ),
    ]
