# Generated by Django 5.2.7 on 2025-10-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_tugas_deadline_alter_tugas_bab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='bab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_list', to='learning.bab'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='judul',
            field=models.CharField(max_length=200),
        ),
    ]
