# Generated by Django 5.2.7 on 2025-10-27 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_pengumpulantugas_tugas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengumpulantugas',
            old_name='tanggal_kumpul',
            new_name='waktu_dikumpulkan',
        ),
        migrations.AddField(
            model_name='pengumpulantugas',
            name='komentar_guru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tugas/'),
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='nilai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='tugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tugas'),
        ),
    ]
