# Generated by Django 5.2.7 on 2025-10-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_rename_tanggal_kumpul_pengumpulantugas_waktu_dikumpulkan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='tugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan_tugas', to='learning.tugas'),
        ),
    ]
