# Generated by Django 5.2.7 on 2025-10-27 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_pengumpulantugas_tugas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpa', 'Alpa')], max_length=10)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.guruprofile')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.mapel')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.siswaprofile')),
            ],
            options={
                'unique_together': {('siswa', 'mapel', 'tanggal')},
            },
        ),
    ]
