# Generated by Django 5.2.7 on 2025-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_absensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumpulantugas',
            name='teks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
