# Generated by Django 5.2.7 on 2025-10-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_pengumpulantugas_teks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengumpulantugas',
            old_name='file',
            new_name='jawaban_file',
        ),
        migrations.RenameField(
            model_name='pengumpulantugas',
            old_name='teks',
            new_name='jawaban_teks',
        ),
    ]
