# Generated by Django 5.2.7 on 2025-10-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_rename_file_pengumpulantugas_jawaban_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='file_tugas',
            field=models.FileField(blank=True, null=True, upload_to='tugas_files/'),
        ),
    ]
