# Generated by Django 5.2.7 on 2025-11-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_tugas_file_tugas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guruprofile',
            name='kelas',
        ),
        migrations.AddField(
            model_name='guruprofile',
            name='kelas_diajar',
            field=models.ManyToManyField(blank=True, related_name='guru_yang_mengajar', to='learning.kelas'),
        ),
    ]
