# Generated by Django 5.2.7 on 2026-04-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_remove_guruprofile_kelas_guruprofile_kelas_diajar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapel',
            name='guru',
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='jawaban_file',
            field=models.FileField(blank=True, null=True, upload_to='jawaban/'),
        ),
    ]
