# Generated by Django 5.2.7 on 2026-04-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_remove_mapel_guru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapel_diajarkan', to='learning.guruprofile'),
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='jawaban_file',
            field=models.FileField(blank=True, null=True, upload_to='tugas/'),
        ),
    ]
