# Generated by Django 5.2.7 on 2026-04-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_mapel_guru_alter_pengumpulantugas_jawaban_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapel',
            name='guru',
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='jawaban_file',
            field=models.FileField(blank=True, null=True, upload_to='jawaban/'),
        ),
    ]
