# Generated by Django 5.2.7 on 2026-05-10 02:28

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_mapel_guru_alter_pengumpulantugas_jawaban_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=learning.models.upload_gambar_mapel),
        ),
        migrations.AlterField(
            model_name='pengumpulantugas',
            name='jawaban_file',
            field=models.FileField(blank=True, null=True, upload_to=learning.models.upload_jawaban_siswa),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='file_tugas',
            field=models.FileField(blank=True, null=True, upload_to=learning.models.upload_file_tugas),
        ),
        migrations.AlterUniqueTogether(
            name='pengumpulantugas',
            unique_together={('tugas', 'siswa')},
        ),
    ]
